### ISSUE TITLE
Migrate to Java 21

### ISSUE THREAD

**Issue by josdem** [josdem/jugoterapia-webflux#34]
As **developer**, I want to migrate to Java 21st **so that** I can use the latest features of Java

**Acceptance Criteria**
- I can see Java 21 in the configuration
- All test are passing

**Comment by josdem** [comment]
17th looks good; let's see how it goes.

**Comment by mslowiak** [comment]
@josdem 
Update to JDK 17 was necessary to make any changes related to spring 3.0 👍 

Upgrade to JDK 21 can still be valid, but it is not blocking any other task I guess
