### ISSUE TITLE
Migrate controllers from WebFlux to Web

### ISSUE THREAD

**Issue by josdem** [josdem/jugoterapia-webflux#35]
As **developer**, I want to migrate controllers from WebFlux to Web **so that** I can only use Spring Boot web features.

**Acceptance Criteria**
- I do not see any `Mono` or `Flux` subscription endpoints
- I do not have WebFlux components in controllers

**Comment by kirillsinyuk** [comment]
Good day. You can assign this one on me

**Comment by josdem** [comment]
Hey, @kirillsinyuk; nice to see you again and collaborate on a project. Sure, I appreciate your help!

**Comment by kirillsinyuk** [comment]
btw, I have a couple of questions about this task:
1) what response is expected from the `getBeverage` handler if no result is found? Usually, there should be 404, but in this case, it might be a breach of contract.
2) there are some things that still have `webflux` mention. like packaging or some references in README.md. Just a reminder, in case you wanna change that.

**Comment by josdem** [comment]
> btw, I have a couple of questions about this task:
> 
> 1. what response is expected from the `getBeverage` handler if no result is found? Usually, there should be 404, but in this case, it might be a breach of contract.
> 2. there are some things that still have `webflux` mention. like packaging or some references in README.md. Just a reminder, in case you wanna change that.

Hi @kirillsinyuk here are my answers:
1. You are right; there is a miss in the design; it should return 404 when a beverage is not found. I created an issue to cover this missing functionality: https://github.com/josdem/jugoterapia-webflux/issues/42
2. Definitely, we should update `README.md` accordingly, also I want to change the repository name, since we will not use Webflux in controllers.

**Comment by josdem** [comment]
All tests passing: 
![35](https://github.com/josdem/jugoterapia-webflux/assets/1222062/16a8f3e3-f186-4df8-9a6c-79753e9fe342)
